const ACCENT = '#879D1F'
const NAVY   = '#031632'

const KPI_COLORS = ['#2196C8', '#3DAA6A', ACCENT, '#D4A017', '#2196C8', '#3DAA6A']

function fmtDate(s) {
  if (!s) return '—'
  return new Date(s).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' })
}

function reportId(prefix = 'RPT') {
  return `${prefix}-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2, 6).toUpperCase()}`
}

/**
 * Build a complete HTML string for a ResQ report PDF.
 *
 * @param {object} opts
 * @param {string}   opts.title        - Large heading, e.g. "District Executive Report"
 * @param {string}   opts.subtitle     - Small sub-heading shown in the header
 * @param {string}   opts.reportType   - Pill label on meta bar right side, e.g. "EXECUTIVE REPORT"
 * @param {string}   opts.idPrefix     - 2-3 char prefix for the Document ID, e.g. "EXE"
 * @param {object[]} opts.metaItems    - [{label, value}] shown in the meta bar (max 5)
 * @param {object[]} opts.kpis         - [{label, value, sub?}] KPI cards
 * @param {string[]} opts.sections     - Array of raw HTML strings for content sections (tables, text blocks)
 * @param {string}   opts.generatedBy  - Name shown in signature block
 * @param {string}   opts.generatedRole- Role shown in signature block
 */
export function buildPdfHtml({
  title,
  subtitle = '',
  reportType = 'REPORT',
  idPrefix = 'RPT',
  metaItems = [],
  kpis = [],
  sections = [],
  generatedBy = 'System',
  generatedRole = '',
}) {
  const id  = reportId(idPrefix)
  const now = new Date()
  const logo = window.location.origin + '/Rwanda_National_Police.png'
  const nowStr = now.toLocaleString('en-GB', { dateStyle: 'long', timeStyle: 'short' })

  const kpiCards = kpis.map(({ label, value, sub }, idx) => {
    const color = KPI_COLORS[idx % KPI_COLORS.length]
    return `
      <div style="background:${hexAlpha(color, 0.10)};border-left:4px solid ${color};border-radius:8px;padding:14px">
        <div style="font-size:28px;font-weight:800;font-family:monospace;color:${color};line-height:1;margin-bottom:5px">${value ?? '—'}</div>
        <div style="font-size:11px;font-weight:600;color:${darken(color)}">${label}</div>
        ${sub ? `<div style="font-size:10px;color:${color};margin-top:2px">${sub}</div>` : ''}
      </div>`
  }).join('')

  const cols = kpis.length <= 3 ? kpis.length : kpis.length <= 4 ? 4 : 3
  const metaRow = metaItems.map(({ label, value }) =>
    `<div style="font-size:11px;color:#374151;padding-right:16px;border-right:1px solid #cbd5e0;margin-right:16px"><strong style="color:${NAVY}">${label}:</strong> ${value}</div>`
  ).join('')

  const sigBlock = `
    <div style="margin-top:40px;page-break-inside:avoid">
      <div style="font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:0.1em;color:${NAVY};border-bottom:2px solid ${ACCENT};padding-bottom:6px;margin-bottom:24px">
        Authorization &amp; Certification
      </div>
      <div style="display:grid;grid-template-columns:repeat(3,1fr);gap:32px">
        <div>
          <div style="font-size:10px;font-weight:700;text-transform:uppercase;color:#6b7280;margin-bottom:12px">Generated By</div>
          <div style="border-bottom:1px solid #1a202c;height:40px;margin-bottom:6px;position:relative">
            <div style="position:absolute;bottom:4px;left:0;font-size:12px;font-weight:600;color:#1a202c">${generatedBy}</div>
          </div>
          <div style="font-size:11px;color:#374151">${generatedRole}</div>
          <div style="font-size:10px;color:#6b7280;margin-top:2px">${now.toLocaleDateString('en-GB', { dateStyle: 'long' })}</div>
        </div>
        <div>
          <div style="font-size:10px;font-weight:700;text-transform:uppercase;color:#6b7280;margin-bottom:12px">Reviewed &amp; Approved By</div>
          <div style="border-bottom:1px solid #1a202c;height:40px;margin-bottom:6px"></div>
          <div style="font-size:11px;color:#374151">Name &amp; Title</div>
          <div style="font-size:10px;color:#6b7280;margin-top:2px">Date: _______________</div>
        </div>
        <div>
          <div style="font-size:10px;font-weight:700;text-transform:uppercase;color:#6b7280;margin-bottom:12px">Official Stamp</div>
          <div style="border:2px dashed #cbd5e0;border-radius:8px;width:100px;height:80px;display:flex;align-items:center;justify-content:center;margin:0 auto">
            <div style="font-size:9px;color:#9ca3af;text-align:center;font-weight:600;text-transform:uppercase;letter-spacing:0.05em">Place Official<br>Stamp Here</div>
          </div>
        </div>
      </div>
    </div>`

  return `<!DOCTYPE html><html lang="en"><head>
  <meta charset="UTF-8">
  <title>RNP ResQ — ${title} — ${id}</title>
  <style>
    *{box-sizing:border-box;margin:0;padding:0}
    body{font-family:'Segoe UI',Arial,sans-serif;color:#1a202c;background:#fff;font-size:13px}
    @media print{body{-webkit-print-color-adjust:exact;print-color-adjust:exact}@page{margin:8mm 10mm}.no-break{page-break-inside:avoid}}
  </style>
</head><body>

<!-- HEADER -->
<div style="background:linear-gradient(135deg,${NAVY} 0%,#010c1f 100%);color:#fff;padding:22px 32px;display:flex;align-items:center;gap:20px">
  <img src="${logo}" style="width:68px;height:68px;object-fit:contain;flex-shrink:0" alt="RNP Logo" onerror="this.style.display='none'">
  <div style="flex:1">
    <div style="font-size:10px;font-weight:700;letter-spacing:0.15em;text-transform:uppercase;color:#b8c74e;margin-bottom:5px">Rwanda National Police · ResQ Emergency Response Division</div>
    <div style="font-size:22px;font-weight:800;letter-spacing:0.01em;margin-bottom:3px">${title.toUpperCase()}</div>
    ${subtitle ? `<div style="font-size:12px;color:rgba(183,199,78,0.75)">${subtitle}</div>` : ''}
  </div>
  <div style="background:rgba(255,255,255,0.1);border:1px solid rgba(255,255,255,0.2);border-radius:8px;padding:10px 16px;text-align:center;min-width:130px">
    <div style="font-size:9px;font-weight:700;letter-spacing:0.12em;text-transform:uppercase;color:#b8c74e;margin-bottom:4px">Document ID</div>
    <div style="font-size:11px;font-weight:700;color:#fff;font-family:monospace">${id}</div>
    <div style="font-size:9px;color:rgba(183,199,78,0.75);margin-top:3px">&#10003; Official Report</div>
  </div>
</div>

<!-- META BAR -->
<div style="background:#f0f4f8;border-bottom:3px solid ${ACCENT};padding:11px 32px;display:flex;align-items:center;flex-wrap:wrap;gap:0">
  ${metaRow}
  <div style="font-size:11px;color:#374151;padding-right:16px;border-right:1px solid #cbd5e0;margin-right:16px"><strong style="color:${NAVY}">Generated:</strong> ${nowStr}</div>
  <div style="font-size:11px;color:#374151"><strong style="color:${NAVY}">Prepared by:</strong> ${generatedBy}${generatedRole ? ` (${generatedRole})` : ''}</div>
  <div style="margin-left:auto;background:${ACCENT};color:#fff;font-size:10px;font-weight:700;letter-spacing:0.07em;text-transform:uppercase;padding:5px 12px;border-radius:4px">${reportType}</div>
</div>

<!-- CONTENT -->
<div style="padding:26px 32px;display:flex;flex-direction:column;gap:24px">

  ${kpis.length ? `
  <div class="no-break">
    <div style="font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:0.1em;color:${NAVY};border-bottom:2px solid ${ACCENT};padding-bottom:6px;margin-bottom:14px">Key Performance Indicators</div>
    <div style="display:grid;grid-template-columns:repeat(${cols},1fr);gap:12px">${kpiCards}</div>
  </div>` : ''}

  ${sections.join('\n')}

  ${sigBlock}

</div>

<!-- FOOTER -->
<div style="padding:10px 32px 16px;border-top:1px solid #e2e8f0;display:flex;justify-content:space-between">
  <div style="font-size:10px;color:#9ca3af">Rwanda National Police · ResQ Emergency Response Platform · ${id}</div>
  <div style="font-size:10px;color:#9ca3af">Generated ${now.toLocaleString('en-GB', { dateStyle: 'medium', timeStyle: 'short' })}</div>
</div>

</body></html>`
}

export function openPdfWindow(html) {
  const win = window.open('', '_blank')
  if (!win) return
  win.document.write(html)
  win.document.close()
  win.focus()
  setTimeout(() => win.print(), 800)
}

export function sectionHtml(heading, bodyHtml) {
  return `
  <div class="no-break">
    <div style="font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:0.1em;color:${NAVY};border-bottom:2px solid ${ACCENT};padding-bottom:6px;margin-bottom:12px">${heading}</div>
    ${bodyHtml}
  </div>`
}

export function tableHtml(headers, rows) {
  const thCells = headers.map(h => `<th style="padding:10px 14px;text-align:left;font-size:11px;font-weight:600">${h}</th>`).join('')
  const trRows = rows.map((cells, ri) =>
    `<tr style="background:${ri % 2 === 1 ? '#f8fafc' : '#fff'}">${cells.map(c => `<td style="padding:9px 14px;border-bottom:1px solid #e2e8f0;font-size:12px">${c}</td>`).join('')}</tr>`
  ).join('')
  return `<table style="width:100%;border-collapse:collapse;font-size:12px">
    <thead><tr style="background:${NAVY};color:#fff">${thCells}</tr></thead>
    <tbody>${trRows || `<tr><td colspan="${headers.length}" style="padding:12px;color:#6b7280;text-align:center">No data available</td></tr>`}</tbody>
  </table>`
}

function hexAlpha(hex, alpha) {
  const r = parseInt(hex.slice(1, 3), 16)
  const g = parseInt(hex.slice(3, 5), 16)
  const b = parseInt(hex.slice(5, 7), 16)
  return `rgba(${r},${g},${b},${alpha})`
}

function darken(hex) {
  const r = Math.max(0, parseInt(hex.slice(1, 3), 16) - 40)
  const g = Math.max(0, parseInt(hex.slice(3, 5), 16) - 40)
  const b = Math.max(0, parseInt(hex.slice(5, 7), 16) - 40)
  return `rgb(${r},${g},${b})`
}
