import { useState, useEffect } from 'react'
import { Download, Search, FileCheck, ClipboardList, Timer, ShieldCheck, ListFilter } from 'lucide-react'
import ViewClosureModal from '../../components/dispatcher/ViewClosureModal'
import AdminStatCard from '../../components/admin/AdminStatCard'
import FilterDropdown from '../../components/admin/FilterDropdown'
import AdminPagination from '../../components/admin/AdminPagination'
import { listIncidents } from '../../api/incidents'
import { listDispatchesForIncident } from '../../api/dispatches'
import { listDistricts } from '../../api/districts'
import { getResponseTimeTarget } from '../../api/admin'
import { buildPdfHtml, openPdfWindow, sectionHtml, tableHtml } from '../../utils/pdfExport'
import { formatIncidentType, normalizeIncidentType } from '../../utils/incidentTypeLabels'

const RANGE_OPTIONS = [
  { value: 'all',   label: 'All Time' },
  { value: '7d',    label: 'Last 7 Days' },
  { value: '30d',   label: 'Last 30 Days' },
  { value: 'month', label: 'This Month' },
]

function inRange(callTime, range) {
  if (range === 'all' || !callTime) return true
  const t = new Date(callTime)
  const now = new Date()
  if (range === '7d')    return t >= new Date(now - 7 * 86400000)
  if (range === '30d')   return t >= new Date(now - 30 * 86400000)
  if (range === 'month') return t.getFullYear() === now.getFullYear() && t.getMonth() === now.getMonth()
  return true
}

function exportPDF(rows, { totalCount, avgResponse, slaPct, slaTargetMinutes }) {
  const generatedBy = sessionStorage.getItem('resq-full-name') || 'Dispatcher'
  const sevColor = { critical: '#B9382F', high: '#F07820', medium: '#D4A017', low: '#3DAA6A' }
  const rows20 = rows.slice(0, 20)
  const tableSection = sectionHtml(
    `Incident Log${rows.length > 20 ? ` (first 20 of ${rows.length})` : ''}`,
    tableHtml(
      ['Ref', 'Type', 'Severity', 'District', 'Call Time', 'Response', 'Status'],
      rows20.map(r => {
        const sc = sevColor[(r.severity || '').toLowerCase()] || '#888'
        const ct = r.call_time ? new Date(r.call_time).toLocaleDateString('en-GB') : '—'
        return [
          `<span style="font-family:monospace;font-weight:700">${r.incident_ref ?? '—'}</span>`,
          r.incident_type ?? '—',
          `<span style="display:inline-block;padding:2px 7px;border-radius:12px;font-size:10px;font-weight:700;color:#fff;background:${sc}">${(r.severity ?? '—').toUpperCase()}</span>`,
          r.district ?? '—',
          `<span style="font-family:monospace">${ct}</span>`,
          `<span style="font-family:monospace">${r.response_time_minutes != null ? r.response_time_minutes + 'm' : '—'}</span>`,
          r.status ?? '—',
        ]
      })
    )
  )
  openPdfWindow(buildPdfHtml({
    title: 'Incident History Report',
    subtitle: 'Closed Incidents',
    reportType: 'INCIDENT REPORT',
    idPrefix: 'INC',
    metaItems: [
      { label: 'Generated By', value: generatedBy },
      { label: 'Filtered Results', value: `${rows.length} incidents` },
    ],
    kpis: [
      { label: 'Total Incidents', value: totalCount, sub: 'Matching filter' },
      { label: 'Avg Response Time', value: avgResponse != null ? `${avgResponse} min` : 'N/A', sub: `Target < ${slaTargetMinutes} min` },
      { label: `Within SLA (≤${slaTargetMinutes} min)`, value: slaPct != null ? `${slaPct}%` : 'N/A', sub: 'SLA threshold' },
      { label: 'Shown in Report', value: rows.length, sub: rows.length > 20 ? 'First 20 shown' : 'All shown' },
    ],
    sections: [tableSection],
    generatedBy,
    generatedRole: 'Dispatcher',
  }))
}

function exportCsv(rows) {
  const cols = ['incident_ref', 'severity', 'incident_type', 'district', 'sector', 'call_time', 'response_time_minutes', 'resolution_time_minutes', 'status']
  const esc = (v) => `"${String(v ?? '').replace(/"/g, '""')}"`
  const csv = [cols.join(','), ...rows.map((r) => cols.map((c) => esc(r[c])).join(','))].join('\n')
  const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv' }))
  const a = document.createElement('a')
  a.href = url
  a.download = `incident-history-${new Date().toISOString().slice(0, 10)}.csv`
  a.click()
  URL.revokeObjectURL(url)
}

const severityColor = { critical: '#E8354A', high: '#F07820', medium: '#D4A017', low: '#3DAA6A' }

function fmtMinutes(m) {
  if (m == null) return 'N/A'
  return m < 60 ? `${m}m` : `${Math.floor(m / 60)}h ${m % 60}m`
}

export default function IncidentHistory() {
  const [viewClosureIncident, setViewClosureIncident] = useState(null)
  const [search, setSearch] = useState('')
  const [page,   setPage]   = useState(1)
  const [incidents, setIncidents] = useState([])
  const [loading, setLoading] = useState(true)
  const [range, setRange] = useState('all')
  const [typeFilter, setTypeFilter] = useState('All')
  const [districtFilter, setDistrictFilter] = useState('All')
  const [districts, setDistricts] = useState([])
  // Default (8) matches the backend's own fallback until the real
  // admin-configured value loads — every "response time vs target" figure
  // on this page used to hardcode its own guess (8 here, 10 elsewhere)
  // instead of reading Admin Settings' National Response Time Target, so
  // changing it there never actually changed what dispatchers saw.
  const [slaTargetMinutes, setSlaTargetMinutes] = useState(8)
  const perPage = 5

  useEffect(() => {
    listDistricts().then(setDistricts).catch(() => {})
    getResponseTimeTarget().then(setSlaTargetMinutes).catch(() => {})
  }, [])

  // District filter is a real backend query param; the rest filter client-side
  useEffect(() => {
    setLoading(true)
    const params = { status: 'CLOSED' }
    if (districtFilter !== 'All') params.districtId = districtFilter
    listIncidents(params)
      .then(setIncidents)
      .catch(() => listIncidents().then(setIncidents).catch(() => {}))
      .finally(() => setLoading(false))
    setPage(1)
  }, [districtFilter])

  // Type options derived from the actual data, deduplicated by canonical
  // type — older/manually-entered incidents stored the human-readable label
  // directly ("Fire") instead of the canonical code ("FIRE"), and "TRAFFIC"
  // was a legacy synonym for "RTA", so without normalizing first this
  // dropdown showed the same real type twice with different underlying
  // values, each filtering to a different (incomplete) subset of results.
  const typeOptions = ['All', ...Array.from(new Set(incidents.map(i => normalizeIncidentType(i.incident_type)).filter(Boolean))).sort()]

  const filtered = incidents.filter(i =>
    (!search ||
      (i.incident_ref ?? '').toLowerCase().includes(search.toLowerCase()) ||
      (i.incident_type ?? '').toLowerCase().includes(search.toLowerCase()) ||
      (i.district ?? i.address ?? '').toLowerCase().includes(search.toLowerCase())) &&
    (typeFilter === 'All' || normalizeIncidentType(i.incident_type) === typeFilter) &&
    inRange(i.call_time, range)
  )

  // These KPI cards used to be computed from the full district-scoped
  // `incidents` list while the table below rendered `filtered` (after
  // search/type/date-range are also applied) — so if those extra filters
  // excluded every row, the table correctly said "No incidents found" while
  // the KPI cards kept showing stats from the wider, pre-filter set. That's
  // exactly the Kicukiro case: 0 rows in the table, but a stale average
  // still displayed above it. Deriving both from the same `filtered` array
  // keeps them consistent no matter what's currently filtered out.
  const totalCount = filtered.length
  const avgResponseMs = filtered.filter(i => i.response_time_minutes != null)
  const avgResponse = avgResponseMs.length
    ? Math.round(avgResponseMs.reduce((s, i) => s + i.response_time_minutes, 0) / avgResponseMs.length)
    : null
  const slaCount = avgResponseMs.filter(i => i.response_time_minutes <= slaTargetMinutes).length
  const slaPct = avgResponseMs.length ? Math.round((slaCount / avgResponseMs.length) * 100) : null
  const totalPages = Math.max(1, Math.ceil(filtered.length / perPage))
  const paged      = filtered.slice((page - 1) * perPage, page * perPage)

  // Units column was hardcoded to "—" for every row — nothing ever fetched
  // which vehicles were actually dispatched. Only fetch for the currently
  // visible page (5 rows), not all filtered results, to keep this cheap.
  const [unitsByIncident, setUnitsByIncident] = useState({})
  useEffect(() => {
    let cancelled = false
    Promise.all(paged.map((inc) =>
      listDispatchesForIncident(inc.incident_id)
        .then((ds) => [inc.incident_id, ds.filter((d) => d.vehicle_plate).map((d) => ({
          plate: d.vehicle_plate,
          isBackup: d.override_reason === 'backup_request',
        }))])
        .catch(() => [inc.incident_id, []])
    )).then((entries) => {
      if (cancelled) return
      setUnitsByIncident(Object.fromEntries(entries))
    })
    return () => { cancelled = true }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [page, districtFilter, incidents])

  return (
    <div className="portal-page">

      <div className="flex items-center justify-between mb-5">
        <div>
          <span className="dispatcher-eyebrow">Incident log</span>
          <h1 className="text-2xl font-bold m-0" style={{ fontFamily: 'var(--font-display)' }}>Incident History</h1>
        </div>
        <div className="flex gap-2">
          <button
            onClick={() => exportPDF(filtered, { totalCount, avgResponse, slaPct, slaTargetMinutes })}
            disabled={loading || filtered.length === 0}
            className="flex items-center gap-1.5 px-5 py-2.25 bg-transparent border border-(--border) text-(--text-primary) font-semibold text-[13px] rounded-lg cursor-pointer hover:bg-(--bg-elevated) hover:border-(--accent) transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
            style={{ fontFamily: 'var(--font-body)' }}
          >
            <Download size={14} /> Export PDF
          </button>
          <button
            onClick={() => exportCsv(filtered)}
            disabled={loading || filtered.length === 0}
            className="flex items-center gap-1.5 px-5 py-2.25 bg-transparent border border-(--border) text-(--text-primary) font-semibold text-[13px] rounded-lg cursor-pointer hover:bg-(--bg-elevated) hover:border-(--accent) transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
            style={{ fontFamily: 'var(--font-body)' }}
          >
            <Download size={14} /> Export CSV
          </button>
        </div>
      </div>

      <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-5">
        <AdminStatCard icon={ClipboardList} label="Total Closed" value={loading ? '…' : String(totalCount)} />
        <AdminStatCard icon={Timer} label="Avg Response Time" value={loading ? '…' : (avgResponse != null ? `${avgResponse}m` : 'N/A')} sub={`Target: ${slaTargetMinutes} min`} />
        <AdminStatCard icon={ShieldCheck} label="Within SLA" value={loading ? '…' : (slaPct != null ? `${slaPct}%` : 'N/A')} sub={`Response arrived ≤ ${slaTargetMinutes} min after the call`} />
        <AdminStatCard icon={ListFilter} label="Incidents Shown" value={loading ? '…' : String(filtered.length)} sub="Filtered results" />
      </div>

      <div className="flex flex-nowrap items-center gap-2 mb-4">
        <div className="relative w-56 shrink-0">
          <Search size={13} className="absolute left-3 top-1/2 -translate-y-1/2 text-(--text-muted)" />
          <input
            type="text"
            value={search}
            onChange={e => { setSearch(e.target.value); setPage(1) }}
            placeholder="Search incidents…"
            className="dispatcher-input h-8 w-full rounded-full pl-8 pr-3 text-[11px]"
            style={{ borderRadius: 9999 }}
          />
        </div>
        <FilterDropdown
          label="All Time"
          value={range}
          onChange={(v) => { setRange(v); setPage(1) }}
          options={RANGE_OPTIONS}
        />
        <FilterDropdown
          label="All Types"
          value={typeFilter}
          onChange={(v) => { setTypeFilter(v); setPage(1) }}
          options={typeOptions.map(o => ({ value: o, label: o === 'All' ? 'All Types' : formatIncidentType(o) }))}
        />
        <FilterDropdown
          label="All Districts"
          value={districtFilter}
          onChange={(v) => setDistrictFilter(v)}
          options={[{ value: 'All', label: 'All Districts' }, ...districts.map(d => ({ value: d.district_id, label: d.name }))]}
        />
      </div>

      <div className="dispatcher-surface table-scroll">
        <table className="w-full min-w-[960px] text-left border-collapse text-[12px]">
          <thead>
            <tr className="text-[12px] font-medium text-(--text-secondary) border-b border-(--border-subtle)">
              <th className="py-2 px-3 font-bold whitespace-nowrap">ID</th>
              {['Severity', 'Type', 'District / Sector', 'Reported', 'Response Time', 'Resolution Time', 'Units', 'SLA', 'Action'].map(col => (
                <th key={col} className="py-2 px-3 font-bold text-center whitespace-nowrap">{col}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {loading ? (
              <tr><td colSpan={10} className="px-3.5 py-12 text-center text-[13px] text-(--text-muted)">Loading…</td></tr>
            ) : paged.length === 0 ? (
              <tr><td colSpan={10} className="px-3.5 py-12 text-center text-[13px] text-(--text-muted)">No incidents found.</td></tr>
            ) : paged.map((inc, idx) => {
              const sev = inc.severity ?? 'medium'
              const c = severityColor[sev] || '#44474D'
              const respMins = inc.response_time_minutes
              const withinSla = respMins != null && respMins <= slaTargetMinutes
              const location = inc.district
                ? `${inc.district}${inc.sector ? ' / ' + inc.sector : ''}`
                : (inc.address ?? '—')
              return (
                <tr key={inc.incident_id + idx} className="border-b border-(--border-subtle) last:border-0 dispatcher-table-row">
                  <td className="py-3 px-3">
                    <span className="font-mono text-[12px] font-semibold text-(--accent)">{inc.incident_ref}</span>
                  </td>
                  <td className="py-3 px-3 text-center">
                    <span className="inline-flex items-center px-2.25 py-0.5 rounded text-[10px] font-bold uppercase tracking-[0.07em] border"
                      style={{ background: c + '25', color: c, borderColor: c + '40' }}>
                      {sev.toUpperCase()}
                    </span>
                  </td>
                  <td className="py-3 px-3 text-center">{formatIncidentType(inc.incident_type)}</td>
                  <td className="py-3 px-3 text-center">{location}</td>
                  <td className="py-3 px-3 text-center">
                    {inc.call_time ? new Date(inc.call_time).toLocaleString() : '—'}
                  </td>
                  <td className="py-3 px-3 text-center">
                    <span style={{ color: respMins != null ? (withinSla ? 'var(--status-low)' : 'var(--status-critical)') : 'var(--text-muted)' }}>
                      {fmtMinutes(respMins)}
                    </span>
                  </td>
                  <td className="py-3 px-3 text-center">{fmtMinutes(inc.resolution_time_minutes)}</td>
                  <td className="py-3 px-3 text-center">
                    {(unitsByIncident[inc.incident_id] ?? []).length === 0 ? '—' : (
                      (unitsByIncident[inc.incident_id] ?? []).map((u, i) => (
                        <span key={u.plate + i}>
                          {i > 0 && ', '}
                          {u.plate}
                          {u.isBackup && (
                            <span
                              className="ml-1 text-[9px] font-bold uppercase tracking-wide px-1 py-0.5 rounded"
                              style={{ background: 'var(--status-medium-bg)', color: 'var(--status-medium)' }}
                            >
                              Backup
                            </span>
                          )}
                        </span>
                      ))
                    )}
                  </td>
                  <td className="py-3 px-3 text-center">
                    {respMins != null ? (
                      <span className="inline-flex items-center px-2.25 py-0.5 rounded text-[10px] font-bold uppercase tracking-[0.07em]"
                        style={{
                          background: withinSla ? 'var(--status-low-bg)' : 'var(--status-critical-bg)',
                          color: withinSla ? 'var(--status-low)' : 'var(--status-critical)',
                        }}>
                        {withinSla ? '✓ MET' : '✗ MISSED'}
                      </span>
                    ) : (
                      <span className="text-[10px] text-(--text-muted)">N/A</span>
                    )}
                  </td>
                  <td className="py-3 px-3 text-center">
                    <button
                      type="button"
                      onClick={() => setViewClosureIncident(inc)}
                      className="inline-flex items-center gap-1 px-1 py-1 rounded-lg cursor-pointer text-[11px] font-bold text-(--accent) transition-opacity hover:opacity-70"
                      style={{ background: 'none', border: 'none' }}
                    >
                      <FileCheck size={12} />
                      View Closure
                    </button>
                  </td>
                </tr>
              )
            })}
          </tbody>
        </table>
      </div>

      <AdminPagination page={page} totalPages={totalPages} totalCount={filtered.length} pageSize={perPage} onPageChange={setPage} />

      <ViewClosureModal
        incident={viewClosureIncident}
        open={!!viewClosureIncident}
        onClose={() => setViewClosureIncident(null)}
      />
    </div>
  )
}
