import { useState, useEffect } from 'react'
import { ChevronRight, ChevronLeft, Download, Search, FileCheck } from 'lucide-react'
import ViewClosureModal from '../../components/dispatcher/ViewClosureModal'
import { listIncidents } from '../../api/incidents'
import { listDispatchesForIncident } from '../../api/dispatches'
import { listDistricts } from '../../api/districts'
import { getResponseTimeTarget } from '../../api/admin'
import { buildPdfHtml, openPdfWindow, sectionHtml, tableHtml } from '../../utils/pdfExport'
import { formatIncidentType, normalizeIncidentType } from '../../utils/incidentTypeLabels'

const RANGE_OPTIONS = [
  { value: 'all',   label: 'All Time' },
  { value: '7d',    label: 'Last 7 Days' },
  { value: '30d',   label: 'Last 30 Days' },
  { value: 'month', label: 'This Month' },
]

function inRange(callTime, range) {
  if (range === 'all' || !callTime) return true
  const t = new Date(callTime)
  const now = new Date()
  if (range === '7d')    return t >= new Date(now - 7 * 86400000)
  if (range === '30d')   return t >= new Date(now - 30 * 86400000)
  if (range === 'month') return t.getFullYear() === now.getFullYear() && t.getMonth() === now.getMonth()
  return true
}

function exportPDF(rows, { totalCount, avgResponse, slaPct, slaTargetMinutes }) {
  const generatedBy = sessionStorage.getItem('resq-full-name') || 'Dispatcher'
  const sevColor = { critical: '#B9382F', high: '#F07820', medium: '#D4A017', low: '#3DAA6A' }
  const rows20 = rows.slice(0, 20)
  const tableSection = sectionHtml(
    `Incident Log${rows.length > 20 ? ` (first 20 of ${rows.length})` : ''}`,
    tableHtml(
      ['Ref', 'Type', 'Severity', 'District', 'Call Time', 'Response', 'Status'],
      rows20.map(r => {
        const sc = sevColor[(r.severity || '').toLowerCase()] || '#888'
        const ct = r.call_time ? new Date(r.call_time).toLocaleDateString('en-GB') : '—'
        return [
          `<span style="font-family:monospace;font-weight:700">${r.incident_ref ?? '—'}</span>`,
          r.incident_type ?? '—',
          `<span style="display:inline-block;padding:2px 7px;border-radius:12px;font-size:10px;font-weight:700;color:#fff;background:${sc}">${(r.severity ?? '—').toUpperCase()}</span>`,
          r.district ?? '—',
          `<span style="font-family:monospace">${ct}</span>`,
          `<span style="font-family:monospace">${r.response_time_minutes != null ? r.response_time_minutes + 'm' : '—'}</span>`,
          r.status ?? '—',
        ]
      })
    )
  )
  openPdfWindow(buildPdfHtml({
    title: 'Incident History Report',
    subtitle: 'Closed Incidents',
    reportType: 'INCIDENT REPORT',
    idPrefix: 'INC',
    metaItems: [
      { label: 'Generated By', value: generatedBy },
      { label: 'Filtered Results', value: `${rows.length} incidents` },
    ],
    kpis: [
      { label: 'Total Incidents', value: totalCount, sub: 'Matching filter' },
      { label: 'Avg Response Time', value: avgResponse != null ? `${avgResponse} min` : 'N/A', sub: `Target < ${slaTargetMinutes} min` },
      { label: `Within SLA (≤${slaTargetMinutes} min)`, value: slaPct != null ? `${slaPct}%` : 'N/A', sub: 'SLA threshold' },
      { label: 'Shown in Report', value: rows.length, sub: rows.length > 20 ? 'First 20 shown' : 'All shown' },
    ],
    sections: [tableSection],
    generatedBy,
    generatedRole: 'Dispatcher',
  }))
}

function exportCsv(rows) {
  const cols = ['incident_ref', 'severity', 'incident_type', 'district', 'sector', 'call_time', 'response_time_minutes', 'resolution_time_minutes', 'status']
  const esc = (v) => `"${String(v ?? '').replace(/"/g, '""')}"`
  const csv = [cols.join(','), ...rows.map((r) => cols.map((c) => esc(r[c])).join(','))].join('\n')
  const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv' }))
  const a = document.createElement('a')
  a.href = url
  a.download = `incident-history-${new Date().toISOString().slice(0, 10)}.csv`
  a.click()
  URL.revokeObjectURL(url)
}

const severityColor = { critical: '#E8354A', high: '#F07820', medium: '#D4A017', low: '#3DAA6A' }

function KpiCard({ label, value, sub }) {
  return (
    <div className="flex-1 min-w-40 bg-(--bg-surface) border border-(--border) rounded-xl p-5">
      <div className="text-[12px] text-(--text-secondary) mb-1.5">{label}</div>
      <div className="text-[28px] font-bold leading-none" style={{ fontFamily: 'var(--font-display)' }}>{value}</div>
      {sub && <div className="text-[11px] text-(--text-muted) mt-1">{sub}</div>}
    </div>
  )
}

function fmtMinutes(m) {
  if (m == null) return 'N/A'
  return m < 60 ? `${m}m` : `${Math.floor(m / 60)}h ${m % 60}m`
}

export default function IncidentHistory() {
  const [viewClosureIncident, setViewClosureIncident] = useState(null)
  const [search, setSearch] = useState('')
  const [page,   setPage]   = useState(1)
  const [incidents, setIncidents] = useState([])
  const [loading, setLoading] = useState(true)
  const [range, setRange] = useState('all')
  const [typeFilter, setTypeFilter] = useState('All')
  const [districtFilter, setDistrictFilter] = useState('All')
  const [districts, setDistricts] = useState([])
  // Default (8) matches the backend's own fallback until the real
  // admin-configured value loads — every "response time vs target" figure
  // on this page used to hardcode its own guess (8 here, 10 elsewhere)
  // instead of reading Admin Settings' National Response Time Target, so
  // changing it there never actually changed what dispatchers saw.
  const [slaTargetMinutes, setSlaTargetMinutes] = useState(8)
  const perPage = 5

  useEffect(() => {
    listDistricts().then(setDistricts).catch(() => {})
    getResponseTimeTarget().then(setSlaTargetMinutes).catch(() => {})
  }, [])

  // District filter is a real backend query param; the rest filter client-side
  useEffect(() => {
    setLoading(true)
    const params = { status: 'CLOSED' }
    if (districtFilter !== 'All') params.districtId = districtFilter
    listIncidents(params)
      .then(setIncidents)
      .catch(() => listIncidents().then(setIncidents).catch(() => {}))
      .finally(() => setLoading(false))
    setPage(1)
  }, [districtFilter])

  // Type options derived from the actual data, deduplicated by canonical
  // type — older/manually-entered incidents stored the human-readable label
  // directly ("Fire") instead of the canonical code ("FIRE"), and "TRAFFIC"
  // was a legacy synonym for "RTA", so without normalizing first this
  // dropdown showed the same real type twice with different underlying
  // values, each filtering to a different (incomplete) subset of results.
  const typeOptions = ['All', ...Array.from(new Set(incidents.map(i => normalizeIncidentType(i.incident_type)).filter(Boolean))).sort()]

  const filtered = incidents.filter(i =>
    (!search ||
      (i.incident_ref ?? '').toLowerCase().includes(search.toLowerCase()) ||
      (i.incident_type ?? '').toLowerCase().includes(search.toLowerCase()) ||
      (i.district ?? i.address ?? '').toLowerCase().includes(search.toLowerCase())) &&
    (typeFilter === 'All' || normalizeIncidentType(i.incident_type) === typeFilter) &&
    inRange(i.call_time, range)
  )

  // These KPI cards used to be computed from the full district-scoped
  // `incidents` list while the table below rendered `filtered` (after
  // search/type/date-range are also applied) — so if those extra filters
  // excluded every row, the table correctly said "No incidents found" while
  // the KPI cards kept showing stats from the wider, pre-filter set. That's
  // exactly the Kicukiro case: 0 rows in the table, but a stale average
  // still displayed above it. Deriving both from the same `filtered` array
  // keeps them consistent no matter what's currently filtered out.
  const totalCount = filtered.length
  const avgResponseMs = filtered.filter(i => i.response_time_minutes != null)
  const avgResponse = avgResponseMs.length
    ? Math.round(avgResponseMs.reduce((s, i) => s + i.response_time_minutes, 0) / avgResponseMs.length)
    : null
  const slaCount = avgResponseMs.filter(i => i.response_time_minutes <= slaTargetMinutes).length
  const slaPct = avgResponseMs.length ? Math.round((slaCount / avgResponseMs.length) * 100) : null
  const totalPages = Math.max(1, Math.ceil(filtered.length / perPage))
  const paged      = filtered.slice((page - 1) * perPage, page * perPage)

  // Units column was hardcoded to "—" for every row — nothing ever fetched
  // which vehicles were actually dispatched. Only fetch for the currently
  // visible page (5 rows), not all filtered results, to keep this cheap.
  const [unitsByIncident, setUnitsByIncident] = useState({})
  useEffect(() => {
    let cancelled = false
    Promise.all(paged.map((inc) =>
      listDispatchesForIncident(inc.incident_id)
        .then((ds) => [inc.incident_id, ds.map((d) => d.vehicle_plate).filter(Boolean)])
        .catch(() => [inc.incident_id, []])
    )).then((entries) => {
      if (cancelled) return
      setUnitsByIncident(Object.fromEntries(entries))
    })
    return () => { cancelled = true }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [page, districtFilter, incidents])

  return (
    <div className="portal-page">

      <div className="flex items-center justify-between mb-5">
        <div>
          <span className="dispatcher-eyebrow">Incident log</span>
          <h1 className="text-2xl font-bold m-0" style={{ fontFamily: 'var(--font-display)' }}>Incident History</h1>
        </div>
        <div className="flex gap-2">
          <button
            onClick={() => exportPDF(filtered, { totalCount, avgResponse, slaPct, slaTargetMinutes })}
            disabled={loading || filtered.length === 0}
            className="flex items-center gap-1.5 px-5 py-2.25 bg-transparent border border-(--border) text-(--text-primary) font-semibold text-[13px] rounded-lg cursor-pointer hover:bg-(--bg-elevated) hover:border-(--accent) transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
            style={{ fontFamily: 'var(--font-body)' }}
          >
            <Download size={14} /> Export PDF
          </button>
          <button
            onClick={() => exportCsv(filtered)}
            disabled={loading || filtered.length === 0}
            className="flex items-center gap-1.5 px-5 py-2.25 bg-transparent border border-(--border) text-(--text-primary) font-semibold text-[13px] rounded-lg cursor-pointer hover:bg-(--bg-elevated) hover:border-(--accent) transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
            style={{ fontFamily: 'var(--font-body)' }}
          >
            <Download size={14} /> Export CSV
          </button>
        </div>
      </div>

      <div className="flex gap-3 mb-5">
        <KpiCard label="Total Closed" value={loading ? '…' : totalCount} />
        <KpiCard label="Avg Response Time" value={loading ? '…' : (avgResponse != null ? `${avgResponse}m` : 'N/A')} sub={`Target: ${slaTargetMinutes} min`} />
        <KpiCard label="Within SLA (Service Level Agreement)" value={loading ? '…' : (slaPct != null ? `${slaPct}%` : 'N/A')} sub={`Response arrived ≤ ${slaTargetMinutes} min after the call`} />
        <KpiCard label="Incidents Shown" value={loading ? '…' : filtered.length} sub="Filtered results" />
      </div>

      <div className="bg-(--bg-surface) border border-(--border) rounded-xl px-4 py-3 mb-4">
        <div className="flex gap-2.5 flex-wrap items-center">
          <div className="relative flex-1 min-w-50">
            <Search size={14} className="absolute left-2.5 top-1/2 -translate-y-1/2 text-(--text-muted)" />
            <input
              className="h-10 w-full bg-(--bg-input) border border-(--border) rounded-full pl-8 pr-3 text-[13px] text-(--text-primary) outline-none focus:border-(--accent) placeholder:text-(--text-muted)"
              placeholder="Search incidents..." value={search}
              onChange={e => { setSearch(e.target.value); setPage(1) }}
              style={{ fontFamily: 'var(--font-body)' }}
            />
          </div>
          <select
            className="h-10 w-40 bg-(--bg-input) border border-(--border) rounded-lg px-3 text-[13px] text-(--text-primary) outline-none appearance-none cursor-pointer"
            style={{ fontFamily: 'var(--font-body)' }}
            value={range}
            onChange={e => { setRange(e.target.value); setPage(1) }}
          >
            {RANGE_OPTIONS.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}
          </select>
          <select
            className="h-10 w-32 bg-(--bg-input) border border-(--border) rounded-lg px-3 text-[13px] text-(--text-primary) outline-none appearance-none cursor-pointer"
            style={{ fontFamily: 'var(--font-body)' }}
            value={typeFilter}
            onChange={e => { setTypeFilter(e.target.value); setPage(1) }}
          >
            {typeOptions.map(o => <option key={o} value={o}>{o === 'All' ? 'All Types' : formatIncidentType(o)}</option>)}
          </select>
          <select
            className="h-10 w-36 bg-(--bg-input) border border-(--border) rounded-lg px-3 text-[13px] text-(--text-primary) outline-none appearance-none cursor-pointer"
            style={{ fontFamily: 'var(--font-body)' }}
            value={districtFilter}
            onChange={e => setDistrictFilter(e.target.value)}
          >
            <option value="All">All Districts</option>
            {districts.map(d => <option key={d.district_id} value={d.district_id}>{d.name}</option>)}
          </select>
        </div>
      </div>

      <div className="bg-(--bg-surface) border border-(--border) rounded-xl table-scroll">
        <table className="w-full border-collapse min-w-[720px]">
          <thead>
            <tr className="bg-(--bg-base)">
              {['ID', 'Severity', 'Type', 'District / Sector', 'Reported', 'Response Time', 'Resolution Time', 'Units', 'SLA', 'Action'].map(col => (
                <th key={col} className="px-3.5 py-2.5 text-left field-label border-b border-(--border) whitespace-nowrap">{col}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {loading ? (
              <tr><td colSpan={10} className="px-3.5 py-12 text-center text-[13px] text-(--text-muted)">Loading…</td></tr>
            ) : paged.length === 0 ? (
              <tr><td colSpan={10} className="px-3.5 py-12 text-center text-[13px] text-(--text-muted)">No incidents found.</td></tr>
            ) : paged.map((inc, idx) => {
              const sev = inc.severity ?? 'medium'
              const c = severityColor[sev] || '#44474D'
              const respMins = inc.response_time_minutes
              const withinSla = respMins != null && respMins <= slaTargetMinutes
              const location = inc.district
                ? `${inc.district}${inc.sector ? ' / ' + inc.sector : ''}`
                : (inc.address ?? '—')
              return (
                <tr key={inc.incident_id + idx} className="border-b border-(--border-subtle) cursor-pointer hover:bg-(--bg-elevated) transition-colors">
                  <td className="px-3.5 h-12">
                    <span className="text-[12px] font-semibold text-(--accent)" style={{ fontFamily: 'var(--font-mono)' }}>{inc.incident_ref}</span>
                  </td>
                  <td className="px-3.5">
                    <span className="inline-flex items-center px-2.25 py-0.5 rounded text-[10px] font-bold uppercase tracking-[0.07em] border"
                      style={{ background: c + '25', color: c, borderColor: c + '40', fontFamily: 'var(--font-body)' }}>
                      {sev.toUpperCase()}
                    </span>
                  </td>
                  <td className="px-3.5 text-[13px]">{formatIncidentType(inc.incident_type)}</td>
                  <td className="px-3.5 text-[12px] text-(--text-secondary)">{location}</td>
                  <td className="px-3.5 text-[12px] text-(--text-secondary)" style={{ fontFamily: 'var(--font-mono)' }}>
                    {inc.call_time ? new Date(inc.call_time).toLocaleString() : '—'}
                  </td>
                  <td className="px-3.5">
                    <span className="text-[12px] font-semibold" style={{ fontFamily: 'var(--font-mono)', color: respMins != null ? (withinSla ? 'var(--status-low)' : 'var(--status-critical)') : 'var(--text-muted)' }}>
                      {fmtMinutes(respMins)}
                    </span>
                  </td>
                  <td className="px-3.5 text-[12px] text-(--text-secondary)" style={{ fontFamily: 'var(--font-mono)' }}>{fmtMinutes(inc.resolution_time_minutes)}</td>
                  <td className="px-3.5 text-[12px] text-(--status-info)" style={{ fontFamily: 'var(--font-mono)' }}>
                    {(unitsByIncident[inc.incident_id] ?? []).join(', ') || '—'}
                  </td>
                  <td className="px-3.5">
                    {respMins != null ? (
                      <span className="inline-flex items-center px-2.25 py-0.5 rounded text-[10px] font-bold uppercase tracking-[0.07em]"
                        style={{
                          background: withinSla ? 'var(--status-low-bg)' : 'var(--status-critical-bg)',
                          color: withinSla ? 'var(--status-low)' : 'var(--status-critical)',
                          fontFamily: 'var(--font-body)',
                        }}>
                        {withinSla ? '✓ MET' : '✗ MISSED'}
                      </span>
                    ) : (
                      <span className="text-[10px] text-(--text-muted)">N/A</span>
                    )}
                  </td>
                  <td className="px-3.5">
                    <button
                      type="button"
                      onClick={() => setViewClosureIncident(inc)}
                      className="inline-flex items-center gap-1 px-1 py-1 rounded-lg cursor-pointer text-[11px] font-bold text-(--accent) transition-opacity hover:opacity-70"
                      style={{ background: 'none', border: 'none' }}
                    >
                      <FileCheck size={12} />
                      View Closure
                    </button>
                  </td>
                </tr>
              )
            })}
          </tbody>
        </table>

        <div className="flex items-center justify-between px-4 py-3 border-t border-(--border)">
          <span className="text-[12px] text-(--text-muted)">
            Showing {Math.min((page - 1) * perPage + 1, filtered.length)}–{Math.min(page * perPage, filtered.length)} of {filtered.length}
          </span>
          <div className="flex gap-1">
            <button className="p-1.75 rounded-md bg-transparent border-none cursor-pointer text-(--text-secondary) hover:bg-(--bg-elevated) transition-colors disabled:opacity-40"
              onClick={() => setPage(p => Math.max(1, p - 1))} disabled={page === 1}>
              <ChevronLeft size={16} />
            </button>
            {Array.from({ length: totalPages }, (_, i) => i + 1).map(p => (
              <button key={p} onClick={() => setPage(p)}
                className="w-8 h-8 rounded-md border-none cursor-pointer text-[12px] font-semibold transition-colors"
                style={{ background: page === p ? 'var(--accent)' : 'transparent', color: page === p ? 'var(--text-on-accent)' : 'var(--text-secondary)' }}>
                {p}
              </button>
            ))}
            <button className="p-1.75 rounded-md bg-transparent border-none cursor-pointer text-(--text-secondary) hover:bg-(--bg-elevated) transition-colors disabled:opacity-40"
              onClick={() => setPage(p => Math.min(totalPages, p + 1))} disabled={page === totalPages}>
              <ChevronRight size={16} />
            </button>
          </div>
        </div>
      </div>

      <ViewClosureModal
        incident={viewClosureIncident}
        open={!!viewClosureIncident}
        onClose={() => setViewClosureIncident(null)}
      />
    </div>
  )
}
