import { useState, useEffect, useRef } from 'react'
import { useNavigate, useLocation } from 'react-router-dom'
import { FileCheck, Clock, ChevronRight, AlertTriangle, Search, Download } from 'lucide-react'
import { listIncidents } from '../../api/incidents'
import { listDispatchesForIncident } from '../../api/dispatches'
import { formatIncidentType } from '../../utils/incidentTypeLabels'
import { buildPdfHtml, openPdfWindow, sectionHtml, tableHtml } from '../../utils/pdfExport'

function exportPDF(rows) {
  const generatedBy = sessionStorage.getItem('resq-full-name') || 'Dispatcher'
  const sevColor = { critical: '#B9382F', high: '#F07820', medium: '#D4A017', low: '#3DAA6A' }
  const tableSection = sectionHtml(
    'Pending Reports',
    tableHtml(
      ['Ref', 'Type', 'District', 'Severity', 'Call Time', 'Elapsed', 'Unit'],
      rows.map((r) => {
        const sc = sevColor[(r.severity || '').toLowerCase()] || '#888'
        const ct = r.call_time ? new Date(r.call_time).toLocaleString('en-GB') : '—'
        const mins = elapsedMinutes(r.call_time)
        return [
          `<span style="font-family:monospace;font-weight:700">${r.incident_ref ?? '—'}</span>`,
          formatIncidentType(r.incident_type) ?? '—',
          r.district ?? r.address ?? '—',
          `<span style="display:inline-block;padding:2px 7px;border-radius:12px;font-size:10px;font-weight:700;color:#fff;background:${sc}">${(r.severity ?? '—').toUpperCase()}</span>`,
          `<span style="font-family:monospace">${ct}</span>`,
          mins != null ? `${mins}m` : '—',
          (r.units ?? []).join(', ') || '—',
        ]
      })
    )
  )
  openPdfWindow(buildPdfHtml({
    title: 'Pending Reports',
    subtitle: 'Incidents Awaiting Closure',
    reportType: 'PENDING REPORTS',
    idPrefix: 'PND',
    metaItems: [
      { label: 'Generated By', value: generatedBy },
      { label: 'Total', value: `${rows.length} pending` },
    ],
    kpis: [
      { label: 'Pending Reports', value: rows.length },
    ],
    sections: [tableSection],
    generatedBy,
    generatedRole: 'Dispatcher',
  }))
}

function exportCsv(rows) {
  const cols = ['incident_ref', 'incident_type', 'district', 'severity', 'call_time', 'status']
  const esc = (v) => `"${String(v ?? '').replace(/"/g, '""')}"`
  const csv = [cols.join(','), ...rows.map((r) => cols.map((c) => esc(r[c])).join(','))].join('\n')
  const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv' }))
  const a = document.createElement('a')
  a.href = url
  a.download = `pending-reports-${new Date().toISOString().slice(0, 10)}.csv`
  a.click()
  URL.revokeObjectURL(url)
}

// Same severity color map + inline badge markup as IncidentHistory.jsx's
// table, so both tables render severity identically.
const severityColor = { critical: '#E8354A', high: '#F07820', medium: '#D4A017', low: '#3DAA6A' }

function elapsedMinutes(callTime) {
  if (!callTime) return null
  return Math.round((Date.now() - new Date(callTime).getTime()) / 60000)
}

function ElapsedChip({ callTime }) {
  const mins = elapsedMinutes(callTime)
  if (mins == null) return null
  const over60 = mins > 60
  return (
    <span
      className="inline-flex items-center gap-1 text-[10px] font-bold px-2 py-0.5 rounded"
      style={{
        fontFamily: 'var(--font-display)',
        background: over60 ? 'var(--status-critical-bg)' : 'var(--accent-ghost)',
        color: over60 ? 'var(--status-critical)' : 'var(--accent)',
      }}
    >
      <Clock size={10} />
      {mins}m elapsed
    </span>
  )
}

export default function PendingReports() {
  const navigate = useNavigate()
  const { state: navState } = useLocation()
  const completedIncident = navState?.completedIncident ?? null

  const [pendingIncidents, setPendingIncidents] = useState([])
  const [loading, setLoading] = useState(true)
  const [search, setSearch] = useState('')

  // Ref map so we can auto-scroll to the just-completed row
  const rowRefs = useRef({})

  useEffect(() => {
    setLoading(true)
    listIncidents({ status: 'PENDING_REPORT' })
      .then((pending) => {
        // If the DB update hasn't landed yet, inject the completed incident at the top
        if (completedIncident?.incident_id && !pending.some((p) => p.incident_id === completedIncident.incident_id)) {
          pending = [{ ...completedIncident, status: 'PENDING_REPORT' }, ...pending]
        }
        setPendingIncidents(pending)
      })
      .catch(() => {})
      .finally(() => setLoading(false))
  }, []) // eslint-disable-line react-hooks/exhaustive-deps

  // Auto-scroll to the highlighted row once the list renders
  useEffect(() => {
    if (!completedIncident?.incident_id) return
    const el = rowRefs.current[completedIncident.incident_id]
    if (el) el.scrollIntoView({ behavior: 'smooth', block: 'center' })
  }, [pendingIncidents, completedIncident])

  // Unit column was hardcoded to "—" for every row — nothing ever fetched
  // which vehicles were actually dispatched, same gap Incident History had.
  const [unitsByIncident, setUnitsByIncident] = useState({})
  useEffect(() => {
    let cancelled = false
    Promise.all(pendingIncidents.map((inc) =>
      listDispatchesForIncident(inc.incident_id)
        .then((ds) => [inc.incident_id, ds.filter((d) => d.vehicle_plate).map((d) => ({
          plate: d.vehicle_plate,
          isBackup: d.override_reason === 'backup_request',
        }))])
        .catch(() => [inc.incident_id, []])
    )).then((entries) => {
      if (cancelled) return
      setUnitsByIncident(Object.fromEntries(entries))
    })
    return () => { cancelled = true }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [pendingIncidents])

  const filtered = pendingIncidents.filter((i) =>
    !search ||
    (i.incident_ref ?? '').toLowerCase().includes(search.toLowerCase()) ||
    (i.incident_type ?? '').toLowerCase().includes(search.toLowerCase()) ||
    (i.district ?? i.address ?? '').toLowerCase().includes(search.toLowerCase())
  )

  return (
    <div className="portal-page dispatcher-page">
      {/* Page header */}
      <div className="flex items-center justify-between mb-5">
        <div>
          <span className="dispatcher-eyebrow">Reports queue</span>
          <h1
            className="text-2xl font-bold m-0"
            style={{ fontFamily: 'var(--font-display)' }}
          >
            Pending Reports
          </h1>
        </div>
        <div className="flex items-center gap-2">
          {pendingIncidents.length > 0 && (
            <div
              className="inline-flex items-center gap-2 px-3 py-2 rounded-lg text-[12px] font-semibold border"
              style={{
                background: 'var(--accent-ghost)',
                color: 'var(--accent)',
                borderColor: 'color-mix(in srgb, var(--accent) 35%, transparent)',
                fontFamily: 'var(--font-display)',
              }}
            >
              <AlertTriangle size={14} />
              {pendingIncidents.length} report{pendingIncidents.length !== 1 ? 's' : ''} awaiting closure
            </div>
          )}
          <button
            onClick={() => exportPDF(filtered)}
            disabled={loading || filtered.length === 0}
            className="flex items-center gap-1.5 px-5 py-2.25 bg-transparent border border-(--border) text-(--text-primary) font-semibold text-[13px] rounded-lg cursor-pointer hover:bg-(--bg-elevated) hover:border-(--accent) transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
            style={{ fontFamily: 'var(--font-body)' }}
          >
            <Download size={14} /> Export PDF
          </button>
          <button
            onClick={() => exportCsv(filtered)}
            disabled={loading || filtered.length === 0}
            className="flex items-center gap-1.5 px-5 py-2.25 bg-transparent border border-(--border) text-(--text-primary) font-semibold text-[13px] rounded-lg cursor-pointer hover:bg-(--bg-elevated) hover:border-(--accent) transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
            style={{ fontFamily: 'var(--font-body)' }}
          >
            <Download size={14} /> Export CSV
          </button>
        </div>
      </div>

      {/* Filter bar */}
      <div className="bg-(--bg-surface) border border-(--border) rounded-xl px-4 py-3 mb-4">
        <div className="relative max-w-md">
          <Search size={14} className="absolute left-2.5 top-1/2 -translate-y-1/2 text-(--text-muted)" />
          <input
            className="h-10 w-full bg-(--bg-input) border border-(--border) rounded-full pl-8 pr-3 text-[13px] text-(--text-primary) outline-none focus:border-(--accent) placeholder:text-(--text-muted)"
            placeholder="Search pending reports..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            style={{ fontFamily: 'var(--font-body)' }}
          />
        </div>
      </div>

      {/* Table */}
      <div className="bg-(--bg-surface) border border-(--border) rounded-xl table-scroll">
        {loading ? (
          <div className="py-16 text-center text-(--text-muted) text-[13px]">Loading…</div>
        ) : filtered.length === 0 ? (
          <div className="py-16 text-center text-(--text-muted) text-[13px]">
            {pendingIncidents.length === 0
              ? 'No reports pending closure. Closed incidents are on Incident History.'
              : 'No pending reports match your search.'}
          </div>
        ) : (
          <table className="w-full border-collapse min-w-[640px]">
            <thead>
              <tr className="bg-(--bg-base)">
                {['Incident', 'Type', 'District / Sector', 'Severity', 'Call Time', 'Elapsed', 'Unit', 'Action'].map((col) => (
                  <th
                    key={col}
                    className="px-3.5 py-2.5 text-left field-label border-b border-(--border) whitespace-nowrap"
                  >
                    {col}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {filtered.map((inc) => {
                const isJustCompleted = inc.incident_id === completedIncident?.incident_id
                return (
                  <tr
                    key={inc.incident_id}
                    ref={(el) => { if (el) rowRefs.current[inc.incident_id] = el }}
                    className="border-b border-(--border-subtle) transition-colors"
                    style={{
                      background: isJustCompleted
                        ? 'color-mix(in srgb, var(--accent) 8%, transparent)'
                        : undefined,
                      outline: isJustCompleted ? '2px solid var(--accent)' : undefined,
                      outlineOffset: isJustCompleted ? '-2px' : undefined,
                    }}
                  >
                    <td className="px-3.5 h-12">
                      <div className="flex items-center gap-2">
                        <span
                          className="text-[12px] font-semibold text-(--accent)"
                          style={{ fontFamily: 'var(--font-mono)' }}
                        >
                          {inc.incident_ref}
                        </span>
                        {isJustCompleted && (
                          <span
                            className="text-[9px] font-bold uppercase tracking-wider px-1.5 py-0.5 rounded"
                            style={{
                              background: 'var(--accent)',
                              color: '#fff',
                              fontFamily: 'var(--font-display)',
                            }}
                          >
                            Just completed
                          </span>
                        )}
                      </div>
                    </td>
                    <td className="px-3.5 text-[13px]">{formatIncidentType(inc.incident_type)}</td>
                    <td className="px-3.5 text-[12px] text-(--text-secondary)">
                      {inc.district ? `${inc.district}${inc.sector ? ' / ' + inc.sector : ''}` : (inc.address ?? '—')}
                    </td>
                    <td className="px-3.5">
                      {(() => {
                        const sev = inc.severity ?? 'medium'
                        const c = severityColor[sev] || '#44474D'
                        return (
                          <span
                            className="inline-flex items-center px-2.25 py-0.5 rounded text-[10px] font-bold uppercase tracking-[0.07em] border"
                            style={{ background: c + '25', color: c, borderColor: c + '40', fontFamily: 'var(--font-body)' }}
                          >
                            {sev.toUpperCase()}
                          </span>
                        )
                      })()}
                    </td>
                    <td
                      className="px-3.5 text-[12px] text-(--text-secondary)"
                      style={{ fontFamily: 'var(--font-mono)' }}
                    >
                      {inc.call_time ? new Date(inc.call_time).toLocaleString() : '—'}
                    </td>
                    <td className="px-3.5">
                      <ElapsedChip callTime={inc.call_time} />
                    </td>
                    <td
                      className="px-3.5 text-[12px] text-(--status-info)"
                      style={{ fontFamily: 'var(--font-mono)' }}
                    >
                      {(unitsByIncident[inc.incident_id] ?? []).length === 0 ? '—' : (
                        (unitsByIncident[inc.incident_id] ?? []).map((u, i) => (
                          <span key={u.plate + i}>
                            {i > 0 && ', '}
                            {u.plate}
                            {u.isBackup && (
                              <span
                                className="ml-1 text-[9px] font-bold uppercase tracking-wide px-1 py-0.5 rounded"
                                style={{ background: 'var(--status-medium-bg)', color: 'var(--status-medium)', fontFamily: 'var(--font-body)' }}
                              >
                                Backup
                              </span>
                            )}
                          </span>
                        ))
                      )}
                    </td>
                    <td className="px-3.5">
                      <button
                        type="button"
                        onClick={() => navigate('/dispatcher/incident-report', { state: { incident: inc } })}
                        className="inline-flex items-center gap-1 px-3 py-1.5 rounded-lg border-none cursor-pointer text-[11px] font-bold transition-opacity hover:opacity-80"
                        style={{
                          background: 'var(--accent)',
                          color: '#fff',
                          fontFamily: 'var(--font-display)',
                        }}
                      >
                        <FileCheck size={12} />
                        File Report
                        <ChevronRight size={12} />
                      </button>
                    </td>
                  </tr>
                )
              })}
            </tbody>
          </table>
        )}
      </div>
    </div>
  )
}
